name: flutter_hooks_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.6
  built_collection: ^5.0.0
  built_value: ^8.0.0
  http: ^0.13.4
  provider: ^6.0.5
  shared_preferences: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.11
  built_value_generator: ^8.3.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true